version: '3.8'

services:
  servidor_redis_comp: 
    platform: linux/amd64
    image: redis:latest
    networks:
      - nomes_network_compose
  servidor_aplicacao_comp: 
    platform: linux/amd64
    build: 
      dockerfile: build/Dockerfile-app
    ports:
      - "8000:5000"
    env_file: 
      - ./env.dev
    networks:
      - nomes_network_compose    
    volumes:
      - ./src:/app

networks:
  nomes_network_compose: